spring.application.name=flooringpos-api
spring.datasource.url=jdbc:postgresql://localhost:5432/flooringpos
spring.datasource.username=postgres
spring.datasource.password=241002
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api/v1
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration