DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS brands;
DROP TABLE IF EXISTS categories;

CREATE TABLE categories
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE brands
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
);

CREATE TABLE products
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id          INTEGER,
    brand_id             INTEGER,
    name                 VARCHAR(255)   NOT NULL,
    price_per_m2         DECIMAL(12, 2) NOT NULL,
    fitting_price_m2     DECIMAL(12, 2) NOT NULL,
    stock_quantity_units DECIMAL(12, 3) NOT NULL,
    m2_per_unit          DECIMAL(12, 3) NOT NULL,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id),

    CONSTRAINT fk_products_brand
        FOREIGN KEY (brand_id)
            REFERENCES brands (id)
);

CREATE TABLE customers
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    phone      VARCHAR(255)
);
