DROP TABLE IF EXISTS
    lino_details,
    laminate_details,
    carpet_details,
    products,
    fitting_rules,
    brands,
    categories,
    customers
    CASCADE;


CREATE TABLE categories
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE brands
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE fitting_rules
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id            INTEGER        NOT NULL,
    code                   VARCHAR(50)    NOT NULL,
    name                   VARCHAR(100)   NOT NULL,
    fitting_price_m2       DECIMAL(12, 2) NOT NULL,
    minimum_fitting_charge DECIMAL(12, 2) NOT NULL,

    CONSTRAINT fk_fitting_rules_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id),

    CONSTRAINT uq_fitting_rules_category_code
        UNIQUE (category_id, code),

    CONSTRAINT chk_fitting_rules_price
        CHECK (fitting_price_m2 >= 0),

    CONSTRAINT chk_fitting_rules_minimum
        CHECK (minimum_fitting_charge >= 0)
);

CREATE TABLE products
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id      INTEGER        NOT NULL,
    brand_id         INTEGER,
    fitting_rule_id  INTEGER,
    name             VARCHAR(255)   NOT NULL,
    cost_price_m2    DECIMAL(12, 2),
    selling_price_m2 DECIMAL(12, 2) NOT NULL,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id),

    CONSTRAINT fk_products_brand
        FOREIGN KEY (brand_id)
            REFERENCES brands (id),

    CONSTRAINT fk_products_fitting_rule
        FOREIGN KEY (fitting_rule_id)
            REFERENCES fitting_rules (id),

    CONSTRAINT chk_products_cost_price
        CHECK (cost_price_m2 IS NULL OR cost_price_m2 >= 0),

    CONSTRAINT chk_products_selling_price
        CHECK (selling_price_m2 >= 0)
);

CREATE TABLE carpet_details
(
    product_id          INTEGER PRIMARY KEY,
    roll_width_m        DECIMAL(5, 2)  NOT NULL,
    stock_linear_metres DECIMAL(10, 2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_carpet_details_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_carpet_details_roll_width
        CHECK (roll_width_m > 0),

    CONSTRAINT chk_carpet_details_stock
        CHECK (stock_linear_metres >= 0)
);

CREATE TABLE laminate_details
(
    product_id   INTEGER PRIMARY KEY,
    thickness_mm DECIMAL(5, 2),
    style        VARCHAR(30)   NOT NULL DEFAULT 'STANDARD',
    m2_per_box   DECIMAL(8, 3) NOT NULL,
    stock_boxes  INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT fk_laminate_details_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_laminate_details_thickness
        CHECK (thickness_mm IS NULL OR thickness_mm > 0),

    CONSTRAINT chk_laminate_details_m2_per_box
        CHECK (m2_per_box > 0),

    CONSTRAINT chk_laminate_details_stock
        CHECK (stock_boxes >= 0)
);

CREATE TABLE lino_details
(
    product_id          INTEGER PRIMARY KEY,
    roll_width_m        DECIMAL(5, 2)  NOT NULL,
    stock_linear_metres DECIMAL(10, 2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_lino_details_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_lino_details_roll_width
        CHECK (roll_width_m > 0),

    CONSTRAINT chk_lino_details_stock
        CHECK (stock_linear_metres >= 0)
);

CREATE TABLE customers
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    phone      VARCHAR(255)
);