CREATE TABLE products
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id      INTEGER,
    brand_id         INTEGER,
    name             VARCHAR(255)   NOT NULL,
    cost_price_m2    DECIMAL(12, 2) NOT NULL,
    selling_price_m2 DECIMAL(12, 2) NOT NULL,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id),

    CONSTRAINT fk_products_brand
        FOREIGN KEY (brand_id)
            REFERENCES brands (id)
);